// export default {
//   login: 'SamAyodele',
//   id: 22157828,
//   node_id: 'MDQ6VXNlcjIyMTU3ODI4',
//   avatar_url: 'https://avatars.githubusercontent.com/u/22157828?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/SamAyodele',
//   html_url: 'https://github.com/SamAyodele',
//   followers_url: 'https://api.github.com/users/SamAyodele/followers',
//   following_url:
//     'https://api.github.com/users/SamAyodele/following{/other_user}',
//   gists_url: 'https://api.github.com/users/SamAyodele/gists{/gist_id}',
//   starred_url: 'https://api.github.com/users/SamAyodele/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/SamAyodele/subscriptions',
//   organizations_url: 'https://api.github.com/users/SamAyodele/orgs',
//   repos_url: 'https://api.github.com/users/SamAyodele/repos',
//   events_url: 'https://api.github.com/users/SamAyodele/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/SamAyodele/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'Ayodele Abayomi',
//   company: 'Stable Shield Solutions',
//   blog: '',
//   location: 'Abuja, Nigeria',
//   email: null,
//   hireable: true,
//   bio: 'A bird in search of a cage.',
//   twitter_username: 'SirKamara',
//   public_repos: 1,
//   public_gists: 0,
//   followers: 0,
//   following: 0,
//   created_at: '2016-09-12T20:08:43Z',
//   updated_at: '2021-01-30T08:12:25Z',
// };

export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
